### ISSUE TITLE
improve docs

### ISSUE THREAD

**Issue by DGKSK8LIFE** [digitorus/timestamp#7]

**Comment by vanbroup** [comment]
Any specifics you are looking for?

**Comment by DGKSK8LIFE** [comment]
@vanbroup I'd like to see some example code and method descriptions. Thanks.

**Comment by DGKSK8LIFE** [comment]
If you give me a TL;DR about the codebase/what each method does, I could make a PR to improve docs. @vanbroup

**Comment by vanbroup** [comment]
Did you check https://godoc.org/github.com/digitorus/timestamp#pkg-examples ?

I do welcome PR's that improve this package or the documentation.

**Comment by DGKSK8LIFE** [comment]
The hyperlink in the README Is not very easily discernible; maybe make a header hyperlink.

**Comment by vanbroup** [comment]
I added a link in the header, thanks and always interested suggestions and pull requests. Feel free to close this issue if you think it's resolved.
