### ISSUE TITLE
test output mismatch for CN (timestamp_example_test.go)

### ISSUE THREAD

**Issue by florianschroen** [digitorus/timestamp#8]
Hi,

is this output mismatch while `go test` just a CN paring error or a problem while verification? Can this be fixed easily?

```
$ go test
--- FAIL: ExampleCreateRequest_ParseResponse (0.82s)
got:
[140 222 43 143 28 80 96 97 4 176 145 205 188 119 197 142 149 101 26 96 188 163 178 64 230 162 199 171 176 178 173 128]
1.2.3.4.1
CN=www.freetsa.org,OU=TSA,O=Free TSA,L=Wuerzburg,ST=Bayern,C=DE,1.2.840.113549.1.9.1=#0c13627573696c657a617340676d61696c2e636f6d,2.5.4.13=#136d54686973206365727469666963617465206469676974616c6c79207369676e7320646f63756d656e747320616e642074696d65207374616d70207265717565737473206d616465207573696e672074686520667265657473612e6f7267206f6e6c696e65207365727669636573
want:
[140 222 43 143 28 80 96 97 4 176 145 205 188 119 197 142 149 101 26 96 188 163 178 64 230 162 199 171 176 178 173 128]
1.2.3.4.1
CN=www.freetsa.org,OU=TSA,O=Free TSA,L=Wuerzburg,ST=Bayern,C=DE
FAIL
exit status 1
FAIL    github.com/digitorus/timestamp  0.835s
```

```
$ go version
go version go1.15.6 linux/amd64
```

**Comment by vanbroup** [comment]
Thanks for reporting this issue, looks like the subject of the freetsa.org TSA certificate has been updated. This is just impacting this example but had no further impact to this package. 

I get the example updated, probably tomorrow.

**Comment by vanbroup** [comment]
Actually, this is related to an update in go, the subject DN is now  printing all attributes, including the ones go doesn't recognize.

It's just impacting this example, I will get this example updated.

**Comment by vanbroup** [comment]
In Go 1.15 Name.String prints non-standard attributes from Names if ExtraNames is nil:
https://golang.org/doc/go1.15#crypto/x509/pkix

Changed the example output to address this change and resolve the issue.
